# Generated by Django 4.1 on 2022-08-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_alter_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='image',
            field=models.ImageField(default='jobs/7.webp', upload_to='jobs/'),
        ),
    ]
